# try, except, finally
try: 
    # x = 1
    print(x)
except NameError:
    print(NameError)
except:
    print('Error')
else:
    print('Else')
finally: 
    print('Finally')
    